name: Main

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make runnable
        run: chmod +x ./download.sh
      - name: Download dicts
        run: ./download.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./luna_pinyin.extended.dict.yaml
            ./luna_pinyin.extended/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}