name: Main

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+08:00"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Download dicts
        run: |
          python ./tools/baiduspider.py

      - name: Pack outputs
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Dicts.zip luna_pinyin.extended luna_pinyin.extended.dict.yaml

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.current-time.outputs.formattedTime }}"
          files: |
            ./Dicts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}